insert into lord(name, age) VALUES ('John Mayer', 345);
insert into lord(name, age) VALUES ('Eric Clapton', 260);
insert into lord(name, age) VALUES ('John Butler', 114);
insert into lord(name, age) VALUES ('Garri Potter', 400);
insert into lord(name, age) VALUES ('Ahsoka Tano', 15);
insert into planet(name, id_lord) VALUES ('Coruscant', 1);
insert into planet(name, id_lord) VALUES ('Tatooine', 2);
insert into planet(name, id_lord) VALUES ('Korriban', 3);
insert into planet(name, id_lord) VALUES ('Mandalor', 4);
insert into planet(name, id_lord) VALUES ('Naboo', 4);