insert into lord(name, age) VALUES ('John Mayer', 345);
insert into lord(name, age) VALUES ('Eric Clapton', 260);
insert into lord(name, age) VALUES ('John Butler', 114);
insert into lord(name, age) VALUES ('Garri Potter', 400);
insert into lord(name, age) VALUES ('Ahsoka Tano', 15);
insert into lord(name, age) VALUES ('КАЙЛО РЕН', 34);
insert into lord(name, age) VALUES ('Генерал Хакс', 3854);
insert into lord(name, age) VALUES ('КАПИТАН ФАЗМА', 213);
insert into lord(name, age) VALUES ('ЭМИЛИН ХОЛДО', 387);
insert into lord(name, age) VALUES ('ЛЕЯ ОРГАНА', 986);
insert into lord(name, age) VALUES ('R2-D2', 2136);
insert into planet(name, id_lord) VALUES ('Coruscant', 1);
insert into planet(name, id_lord) VALUES ('Tatooine', 2);
insert into planet(name, id_lord) VALUES ('Korriban', 3);
insert into planet(name, id_lord) VALUES ('Mandalor', 4);
insert into planet(name, id_lord) VALUES ('Naboo', 4);
insert into planet(name, id_lord) VALUES ('Alderaan', 5);
insert into planet(name, id_lord) VALUES ('Kamino ', 6);
insert into planet(name, id_lord) VALUES ('Vortex ', 7);
insert into planet(name, id_lord) VALUES ('Ando Prime ', 7);
insert into planet(name, id_lord) VALUES ('Giju ', 9);
insert into planet(name, id_lord) VALUES ('Gravlex Med ', 11);